import Head from 'next/head';
import favicon from '@/assets/images/favicon.ico';
import { makeTitle } from '@/lib';

export default function Home() {
    return (
        <>
            <Head>
                <title>{makeTitle('My Next App')}</title>
                <meta name="author" content="Deepesh Gupta" />
                <meta name="description" content="Generated by my next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href={favicon.src} />
            </Head>
        </>
    );
}
